### ISSUE TITLE
E2 - H14A (Articular-se em equipe de trabalho)

### ISSUE THREAD

**Issue by johntvale** [ICEI-PUC-Minas-PMV-SInt/pmv-sint-2023-2-e3-proj-back-t1-nutripuc#24]
Articular-se em equipe de trabalho: demonstrar capacidade de comunicação e colaboração em um processo de desenvolvimento de software.
**Demonstrou** capacidade de comunicação e colaboração em um processo de desenvolvimento de software e **utilizou ferramentas específicas para gestão da comunicação e colaboração.**

**Comment by lucaspedroabreu** [comment]
Já estamos utilizando nos articulando em grupo!!
Avaliação será com base na percepção do professor (INDAGAR ELE)!!!!!

O que configura utilizar ferramentas específicas para gestão da comunicação e colaboração?
