### ISSUE TITLE
E2 - H14B (utilizar a metodologia ágil )

### ISSUE THREAD

**Issue by johntvale** [ICEI-PUC-Minas-PMV-SInt/pmv-sint-2023-2-e3-proj-back-t1-nutripuc#25]
Articular-se em equipe de trabalho: utilizar a metodologia ágil no desenvolvimento colaborativo de um sistema web.
**Utilizou** a metodologia ágil no desenvolvimento colaborativo de um sistema web **demonstrando organização e eficiência**.

**Comment by lucaspedroabreu** [comment]
Já estamos utilizando a metodologia ágil!
Avaliação será com base na percepção do professor (INDAGAR ELE)!!!!!

O que configura demonstrar organização e eficiência?
